#!/usr/bin/env node
/**
 * Generates supabase/seed.sql from src/data/challenges.json.
 *
 * Deterministic (sorted by id, stable key order) and idempotent (upsert on id),
 * so re-running `supabase db reset` or pasting seed.sql twice is safe.
 *
 * Usage: node supabase/scripts/generate-seed.mjs [input.json] [output.sql]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const input = resolve(process.argv[2] ?? `${root}/src/data/challenges.json`);
const output = resolve(process.argv[3] ?? `${root}/supabase/seed.sql`);

const TRACKS = ['rookie', 'challenger', 'strategist'];
const KINDS = ['rules', 'court-position', 'shot-choice'];

function fail(msg) {
  console.error(`generate-seed: ${msg}`);
  process.exit(1);
}

const challenges = JSON.parse(readFileSync(input, 'utf8'));
if (!Array.isArray(challenges)) fail('input must be a JSON array');

// Light structural checks; full zod validation lives in src/data (client) and SQL constraints (server).
const ids = new Set();
for (const c of challenges) {
  const where = `challenge ${c?.id ?? '(no id)'}`;
  if (!/^(rookie|challenger|strategist)-\d{2,3}$/.test(c.id ?? '')) fail(`${where}: bad id`);
  if (ids.has(c.id)) fail(`${where}: duplicate id`);
  ids.add(c.id);
  if (!TRACKS.includes(c.track)) fail(`${where}: bad track`);
  if (!KINDS.includes(c.kind)) fail(`${where}: bad kind`);
  if (![1, 2, 3].includes(c.difficulty)) fail(`${where}: bad difficulty`);
  if (!Array.isArray(c.options) || c.options.length !== 4) fail(`${where}: needs exactly 4 options`);
  if (!c.options.some((o) => o.id === c.correctOptionId)) fail(`${where}: correctOptionId not in options`);
  if (c.reviewStatus !== 'approved') fail(`${where}: reviewStatus must be 'approved'`);
  for (const k of ['prompt', 'explanation', 'sourceName', 'sourceUrl']) {
    if (typeof c[k] !== 'string' || !c[k].trim()) fail(`${where}: missing ${k}`);
  }
  if (typeof c.coachReviewRequired !== 'boolean') fail(`${where}: coachReviewRequired must be boolean`);
}

const str = (v) => `'${String(v).replaceAll("'", "''")}'`;
const json = (v) => (v === undefined || v === null ? 'null' : `${str(JSON.stringify(v))}::jsonb`);

const sorted = [...challenges].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
const rows = sorted.map((c) => {
  const options = c.options.map((o) => ({ id: o.id, label: o.label }));
  return `  (${[
    str(c.id),
    str(c.track),
    str(c.kind),
    c.difficulty,
    str(c.prompt),
    json(options),
    str(c.correctOptionId),
    str(c.explanation),
    json(c.court),
    str(c.sourceName),
    str(c.sourceUrl),
    'true',
    c.coachReviewRequired ? 'true' : 'false',
  ].join(', ')})`;
});

const sql = `-- GENERATED by supabase/scripts/generate-seed.mjs from src/data/challenges.json.
-- Do not edit by hand; run \`npm run seed:generate\`. Safe to re-run (upsert on id).
-- ${sorted.length} approved challenges.

insert into public.challenges
  (id, track, kind, difficulty, prompt, options, correct_option_id, explanation, court,
   source_name, source_url, approved, coach_review_required)
values
${rows.join(',\n')}
on conflict (id) do update set
  track = excluded.track,
  kind = excluded.kind,
  difficulty = excluded.difficulty,
  prompt = excluded.prompt,
  options = excluded.options,
  correct_option_id = excluded.correct_option_id,
  explanation = excluded.explanation,
  court = excluded.court,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  approved = excluded.approved,
  coach_review_required = excluded.coach_review_required;
`;

writeFileSync(output, sql);
console.log(`generate-seed: wrote ${sorted.length} challenges to ${output}`);
